name:                tetris
version:             0.1.0.0

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- vector
- gloss
- random
- random-shuffle

library:
  source-dirs: src

executables:
  cswk-program-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tetris

tests:
  cswk-program-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tetris
